package unit02.lombok.student;

/**
 * Demonstrates the use of different constructors generated by Lombok.
 */
public class StudentLombokDemoMain {


    public static void main(String[] args) {
        // No-args constructor from @NoArgsConstructor
        Student s = new Student(); 
        
        // Constructor for fields marked with @NonNull from @RequiredArgsConstructor
        Student temp = new Student("Lastname","Firstname","Name"); 
        
        // Full constructor for all fields from @AllArgsConstructor
        Student student = new Student(1, "Name","Firstname","Lastname","email@test.com","12345",true,null) ;

        // Getters provided by @Data
        student.getId();
        student.getEmail();
        
        System.out.println(student);
        System.out.println(s);
        System.out.println(temp);
    }
}
